// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: iotdevice.proto

package server

import (
	"context"

	"rainiot/app/iotdevice/cmd/internal/logic"
	"rainiot/app/iotdevice/cmd/internal/svc"
	"rainiot/pkg/devicecli/grpc/pb"
)

type IotdeviceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedIotdeviceServer
}

func NewIotdeviceServer(svcCtx *svc.ServiceContext) *IotdeviceServer {
	return &IotdeviceServer{
		svcCtx: svcCtx,
	}
}

// 定义一个 DeviceConnect 一元 rpc 方法，请求体和响应体必填。
func (s *IotdeviceServer) DeviceConnect(ctx context.Context, in *pb.DeviceConnectReq) (*pb.DeviceConnectResp, error) {
	l := logic.NewDeviceConnectLogic(ctx, s.svcCtx)
	resp, err := l.DeviceConnect(in).Iotdevice(in)
	if err != nil {
		return nil, err
	}
	return &pb.DeviceConnectResp{
		Message: resp.Message,
	}, nil
}
