// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type Ntice struct {
	Id   string `json:"id"`
	Data []byte `json:"data"`
}

type Request struct {
	ConnId string `path:"connId,options=you|me"`
}

type Response struct {
	Cmd  string `json:"cmd"`
	Data any    `json:"data"`
}

type WsBalanced struct {
	Targeted string `json:"targeted"`
}
