// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Cmd  string `json:"cmd"`
	Data any    `json:"data"`
}

type WsBalanced struct {
	Targeted string `json:"targeted"`
}
