// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	deviceFieldNames          = builder.RawFieldNames(&Device{})
	deviceRows                = strings.Join(deviceFieldNames, ",")
	deviceRowsExpectAutoSet   = strings.Join(stringx.Remove(deviceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	deviceRowsWithPlaceHolder = strings.Join(stringx.Remove(deviceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheDeviceIdPrefix = "cache:device:id:"
)

type (
	deviceModel interface {
		Insert(ctx context.Context, data *Device) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Device, error)
		Update(ctx context.Context, data *Device) error
		Delete(ctx context.Context, id int64) error
	}

	defaultDeviceModel struct {
		sqlc.CachedConn
		table string
	}

	Device struct {
		Id int64  `db:"id"`
		Sn string `db:"sn"`
	}
)

func newDeviceModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultDeviceModel {
	return &defaultDeviceModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`device`",
	}
}

func (m *defaultDeviceModel) Delete(ctx context.Context, id int64) error {
	deviceIdKey := fmt.Sprintf("%s%v", cacheDeviceIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, deviceIdKey)
	return err
}

func (m *defaultDeviceModel) FindOne(ctx context.Context, id int64) (*Device, error) {
	deviceIdKey := fmt.Sprintf("%s%v", cacheDeviceIdPrefix, id)
	var resp Device
	err := m.QueryRowCtx(ctx, &resp, deviceIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", deviceRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDeviceModel) Insert(ctx context.Context, data *Device) (sql.Result, error) {
	deviceIdKey := fmt.Sprintf("%s%v", cacheDeviceIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?)", m.table, deviceRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Sn)
	}, deviceIdKey)
	return ret, err
}

func (m *defaultDeviceModel) Update(ctx context.Context, data *Device) error {
	deviceIdKey := fmt.Sprintf("%s%v", cacheDeviceIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, deviceRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Sn, data.Id)
	}, deviceIdKey)
	return err
}

func (m *defaultDeviceModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheDeviceIdPrefix, primary)
}

func (m *defaultDeviceModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", deviceRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultDeviceModel) tableName() string {
	return m.table
}
