// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/sqlx"
)

var (
	deviceFieldNames          = []string{"id", "sn"}
	deviceRows                = strings.Join(deviceFieldNames, ",")
	deviceRowsExpectAutoSet   = "sn"
	deviceRowsWithPlaceHolder = "sn=$1"
)

type (
	deviceModel interface {
		Insert(ctx context.Context, data *Device) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Device, error)
		FindOneBySn(ctx context.Context, sn string) (*Device, error)
		GetOneBySn(ctx context.Context, sn string) (*Device, bool, error)
		Update(ctx context.Context, data *Device) error
		Delete(ctx context.Context, id int64) error
	}

	defaultDeviceModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Device struct {
		Id int64  `db:"id"`
		Sn string `db:"sn"`
	}
)

func newDeviceModel(conn sqlx.SqlConn) *defaultDeviceModel {
	return &defaultDeviceModel{
		conn:  conn,
		table: "device",
	}
}

func (m *defaultDeviceModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultDeviceModel) FindOne(ctx context.Context, id int64) (*Device, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", deviceRows, m.table)
	var resp Device
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDeviceModel) FindOneBySn(ctx context.Context, sn string) (*Device, error) {
	var resp Device
	query := fmt.Sprintf("select %s from %s where sn = $1 limit 1", deviceRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, sn)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDeviceModel) GetOneBySn(ctx context.Context, sn string) (*Device, bool, error) {
	var resp Device
	query := fmt.Sprintf("select %s from %s where sn = $1 limit 1", deviceRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, sn)
	switch err {
	case nil:
		return &resp, true, nil
	case sqlx.ErrNotFound:
		return nil, false, nil
	default:
		return nil, false, err
	}
}

func (m *defaultDeviceModel) Insert(ctx context.Context, data *Device) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1)", m.table, deviceRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Sn)
	return ret, err
}

func (m *defaultDeviceModel) Update(ctx context.Context, newData *Device) error {
	query := fmt.Sprintf("update %s set %s where id = $2", m.table, deviceRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Sn, newData.Id)
	return err
}

func (m *defaultDeviceModel) tableName() string {
	return m.table
}
