// 声明 proto 语法版本，固定值

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.5
// source: app/iotdevice/iotdevice.proto

// proto 包名

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义请求体
type DeviceConnectReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Sn            string                 `protobuf:"bytes,2,opt,name=sn,proto3" json:"sn,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	ServiceName   string                 `protobuf:"bytes,4,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceConnectReq) Reset() {
	*x = DeviceConnectReq{}
	mi := &file_app_iotdevice_iotdevice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceConnectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceConnectReq) ProtoMessage() {}

func (x *DeviceConnectReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_iotdevice_iotdevice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceConnectReq.ProtoReflect.Descriptor instead.
func (*DeviceConnectReq) Descriptor() ([]byte, []int) {
	return file_app_iotdevice_iotdevice_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceConnectReq) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *DeviceConnectReq) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *DeviceConnectReq) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DeviceConnectReq) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

// 定义响应体
type DeviceConnectResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceConnectResp) Reset() {
	*x = DeviceConnectResp{}
	mi := &file_app_iotdevice_iotdevice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceConnectResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceConnectResp) ProtoMessage() {}

func (x *DeviceConnectResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_iotdevice_iotdevice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceConnectResp.ProtoReflect.Descriptor instead.
func (*DeviceConnectResp) Descriptor() ([]byte, []int) {
	return file_app_iotdevice_iotdevice_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceConnectResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_app_iotdevice_iotdevice_proto protoreflect.FileDescriptor

const file_app_iotdevice_iotdevice_proto_rawDesc = "" +
	"\n" +
	"\x1dapp/iotdevice/iotdevice.proto\x12\tiotdevice\x1a\x1cgoogle/protobuf/struct.proto\"\x83\x01\n" +
	"\x10DeviceConnectReq\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\x12\x0e\n" +
	"\x02sn\x18\x02 \x01(\tR\x02sn\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data\x12 \n" +
	"\vserviceName\x18\x04 \x01(\tR\vserviceName\"-\n" +
	"\x11DeviceConnectResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2W\n" +
	"\tIotdevice\x12J\n" +
	"\rDeviceConnect\x12\x1b.iotdevice.DeviceConnectReq\x1a\x1c.iotdevice.DeviceConnectRespB\x12Z\x10app/iotdevice/pbb\x06proto3"

var (
	file_app_iotdevice_iotdevice_proto_rawDescOnce sync.Once
	file_app_iotdevice_iotdevice_proto_rawDescData []byte
)

func file_app_iotdevice_iotdevice_proto_rawDescGZIP() []byte {
	file_app_iotdevice_iotdevice_proto_rawDescOnce.Do(func() {
		file_app_iotdevice_iotdevice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_iotdevice_iotdevice_proto_rawDesc), len(file_app_iotdevice_iotdevice_proto_rawDesc)))
	})
	return file_app_iotdevice_iotdevice_proto_rawDescData
}

var file_app_iotdevice_iotdevice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_iotdevice_iotdevice_proto_goTypes = []any{
	(*DeviceConnectReq)(nil),  // 0: iotdevice.DeviceConnectReq
	(*DeviceConnectResp)(nil), // 1: iotdevice.DeviceConnectResp
	(*structpb.Struct)(nil),   // 2: google.protobuf.Struct
}
var file_app_iotdevice_iotdevice_proto_depIdxs = []int32{
	2, // 0: iotdevice.DeviceConnectReq.data:type_name -> google.protobuf.Struct
	0, // 1: iotdevice.Iotdevice.DeviceConnect:input_type -> iotdevice.DeviceConnectReq
	1, // 2: iotdevice.Iotdevice.DeviceConnect:output_type -> iotdevice.DeviceConnectResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_iotdevice_iotdevice_proto_init() }
func file_app_iotdevice_iotdevice_proto_init() {
	if File_app_iotdevice_iotdevice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_iotdevice_iotdevice_proto_rawDesc), len(file_app_iotdevice_iotdevice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_iotdevice_iotdevice_proto_goTypes,
		DependencyIndexes: file_app_iotdevice_iotdevice_proto_depIdxs,
		MessageInfos:      file_app_iotdevice_iotdevice_proto_msgTypes,
	}.Build()
	File_app_iotdevice_iotdevice_proto = out.File
	file_app_iotdevice_iotdevice_proto_goTypes = nil
	file_app_iotdevice_iotdevice_proto_depIdxs = nil
}
