// 声明 proto 语法版本，固定值

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.5
// source: app/iotdevice/iotdevice.proto

// proto 包名

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Iotdevice_DeviceConnect_FullMethodName = "/iotdevice.Iotdevice/DeviceConnect"
)

// IotdeviceClient is the client API for Iotdevice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义设备服务
type IotdeviceClient interface {
	// 定义一个 DeviceConnect 一元 rpc 方法，请求体和响应体必填。
	DeviceConnect(ctx context.Context, in *DeviceConnectReq, opts ...grpc.CallOption) (*DeviceConnectResp, error)
}

type iotdeviceClient struct {
	cc grpc.ClientConnInterface
}

func NewIotdeviceClient(cc grpc.ClientConnInterface) IotdeviceClient {
	return &iotdeviceClient{cc}
}

func (c *iotdeviceClient) DeviceConnect(ctx context.Context, in *DeviceConnectReq, opts ...grpc.CallOption) (*DeviceConnectResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceConnectResp)
	err := c.cc.Invoke(ctx, Iotdevice_DeviceConnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IotdeviceServer is the server API for Iotdevice service.
// All implementations must embed UnimplementedIotdeviceServer
// for forward compatibility.
//
// 定义设备服务
type IotdeviceServer interface {
	// 定义一个 DeviceConnect 一元 rpc 方法，请求体和响应体必填。
	DeviceConnect(context.Context, *DeviceConnectReq) (*DeviceConnectResp, error)
	mustEmbedUnimplementedIotdeviceServer()
}

// UnimplementedIotdeviceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIotdeviceServer struct{}

func (UnimplementedIotdeviceServer) DeviceConnect(context.Context, *DeviceConnectReq) (*DeviceConnectResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeviceConnect not implemented")
}
func (UnimplementedIotdeviceServer) mustEmbedUnimplementedIotdeviceServer() {}
func (UnimplementedIotdeviceServer) testEmbeddedByValue()                   {}

// UnsafeIotdeviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IotdeviceServer will
// result in compilation errors.
type UnsafeIotdeviceServer interface {
	mustEmbedUnimplementedIotdeviceServer()
}

func RegisterIotdeviceServer(s grpc.ServiceRegistrar, srv IotdeviceServer) {
	// If the following call panics, it indicates UnimplementedIotdeviceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Iotdevice_ServiceDesc, srv)
}

func _Iotdevice_DeviceConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceConnectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IotdeviceServer).DeviceConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Iotdevice_DeviceConnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IotdeviceServer).DeviceConnect(ctx, req.(*DeviceConnectReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Iotdevice_ServiceDesc is the grpc.ServiceDesc for Iotdevice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Iotdevice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iotdevice.Iotdevice",
	HandlerType: (*IotdeviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeviceConnect",
			Handler:    _Iotdevice_DeviceConnect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/iotdevice/iotdevice.proto",
}
