// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"rainiot/app/iotdevice/cmd/internal/svc"
	"rainiot/pkg/middleware"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/device/connect",
				Handler: middleware.RequestBodyLog(IotdeviceHandler(serverCtx)),
			},
		},
	)
}
