// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type Request struct {
	Cmd         string         `json:"cmd"`
	Sn          string         `json:"sn"`
	Data        map[string]any `json:"data,optional"`
	ServiceName string         `header:"ServiceName"` // 从请求头中提取 ServiceName
}

type Response struct {
	Message string `json:"message"`
}
