name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'  # 或 '1.22.x'
        cache: true           # 启用依赖缓存

    - name: Download dependencies
      run: go mod download    # 显式下载依赖

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Run vet
      run: go vet ./...       # 静态检查（可选）
